# Generated by Django 6.0.1 on 2026-01-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('file', 'File')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, null=True)),
                ('allowed_file_types', models.JSONField(blank=True, null=True)),
                ('max_file_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='applicationsubmission',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.university'),
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='application.university'),
        ),
    ]
